spring.application.name=Trading-Engine

# H2 Local Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Temporarily disable Redis health check/connection on startup if Redis isn't running
spring.data.redis.repositories.enabled=false